networks:
  apstark:
    driver: bridge
services:
  madara:
    image: sotazklabs/madara:latest
    networks:
      - apstark
    restart: unless-stopped
    ports:
      - "9944:9944"
    command: [
      "--devnet",
      "--name=madara",
      "--base-path=../madara_db",
      "--preset=devnet",
      "--rpc-port=9944",
      "--rpc-methods=unsafe",
      "--rpc-cors='*'",
      "--rpc-external",
      "--no-l1-sync",
      "--feeder-gateway-enable",
      "--gateway-enable",
      "--gateway-external",
      "--telemetry-disabled",
    ]

  pathfinder:
    image: sotazklabs/pathfinder:latest
    networks:
      - apstark
    restart: unless-stopped
    ports:
      - "9545:9545"
    env_file:
      - .env
    command: [
      '--network',
      'custom',
      '--chain-id',
      '${MADARA_CHAIN_ID}',
      '--feeder-gateway-url',
      '${FEEDER_GATEWAY_URL}',
      '--gateway-url',
      '${GATEWAY_URL}',
      '--storage.state-tries',
      'archive',
      '--data-directory',
      './pathfinder-db'
    ]

    depends_on:
      - madara